/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registation;

import java.awt.Color;

/**
 *
 * @author nimeshi
 */
public class Dashbord extends javax.swing.JFrame {

    

    /**
     * Creates new form Dashbord
     */
    public Dashbord() {
        initComponents();
        
        // Button Transperants ............................
        Registation.setBackground(new Color(0,0,0,0));
        Registation.setOpaque(false);
        Registation.setContentAreaFilled(false);
        Registation.setBorderPainted(false);
        
        BatchInfo.setBackground(new Color(0,0,0,0));
        BatchInfo.setOpaque(false);
        BatchInfo.setContentAreaFilled(false);
        BatchInfo.setBorderPainted(false);
        
        Courses.setBackground(new Color(0,0,0,0));
        Courses.setOpaque(false);
        Courses.setContentAreaFilled(false);
        Courses.setBorderPainted(false);
        
        Payments.setBackground(new Color(0,0,0,0));
        Payments.setOpaque(false);
        Payments.setContentAreaFilled(false);
        Payments.setBorderPainted(false);
        
        lectures.setBackground(new Color(0,0,0,0));
        lectures.setOpaque(false);
        lectures.setContentAreaFilled(false);
        lectures.setBorderPainted(false);
        /// .....................................
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Registation = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        BatchInfo = new javax.swing.JButton();
        Payments = new javax.swing.JButton();
        Courses = new javax.swing.JButton();
        lectures = new javax.swing.JButton();
        Dashbord = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 42, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registation.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        Registation.setForeground(new java.awt.Color(51, 0, 255));
        Registation.setText("New Registation");
        Registation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistationActionPerformed(evt);
            }
        });
        jPanel1.add(Registation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled-3 copy.png"))); // NOI18N
        jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        BatchInfo.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        BatchInfo.setForeground(new java.awt.Color(255, 0, 153));
        BatchInfo.setText("Batch Info");
        jPanel1.add(BatchInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, -1));

        Payments.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        Payments.setForeground(new java.awt.Color(255, 0, 153));
        Payments.setText("Payments");
        jPanel1.add(Payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 250, -1));

        Courses.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        Courses.setForeground(new java.awt.Color(255, 0, 153));
        Courses.setText("Courses");
        jPanel1.add(Courses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 250, -1));

        lectures.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lectures.setForeground(new java.awt.Color(255, 0, 153));
        lectures.setText("Lectures");
        jPanel1.add(lectures, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        javax.swing.GroupLayout DashbordLayout = new javax.swing.GroupLayout(Dashbord);
        Dashbord.setLayout(DashbordLayout);
        DashbordLayout.setHorizontalGroup(
            DashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        DashbordLayout.setVerticalGroup(
            DashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(Dashbord, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 730, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistationActionPerformed
      Dashbord.removeAll();
       Dashbord.setVisible(true);
       Registation a=new Registation();
      a.setSize(Dashbord.getSize());
      Dashbord.add(a);
      Dashbord.repaint();
      Dashbord.revalidate();
    }//GEN-LAST:event_RegistationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BatchInfo;
    private javax.swing.JButton Courses;
    private javax.swing.JPanel Dashbord;
    private javax.swing.JButton Payments;
    private javax.swing.JButton Registation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lectures;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
